language: java
sudo: false
dist: trusty

addons:
  apt:
    packages:
      - ca-certificates-java
      - openjdk-7-jre-headless

jdk:
  - openjdk7

after_success:
  - if [[ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" == 'master' ]]; then
    mvn deploy --settings .travis-settings.xml -DskipTests=true -B || travis_terminate 1;
    fi

cache:
  directories:
    - $HOME/.m2
